### ISSUE TITLE
Injected uncorrectable errors are not showing up

### ISSUE THREAD

**Issue by sheaushian** [andikleen/mcelog#36]
All other injected error are reported by mcelog (bus/IOMCA, unknown, correctable DIMM/Socket, cache, page) but uncorrectable errors are not reported.
mcelog is running in daemon mode on a broadwell-de (Linux 3.19.5).

I am using the following to generate an uncorrectable error.
GENMEM 0 1 0 1 1 | mce-inject

With tolerant level at default of 1, the system panics as expected.

With tolerant level of 3, no uncorrectable errors are reported by mcelog
echo “3” > /sys/devices/system/machinecheck/machinecheck0/tolerant

**Comment by aegl** [comment]
Is the edac driver (sb_edac for broadwell-de) loaded. Back in 3.19 I think there were issues with edac drivers claiming they fully dealt with errors and not letting them get through to /dev/mcelog. Try "# rmmod sb_edac" and re-run the test.

Though this doesn't explain why you can see correctable memory errors ... what is the full mcelog output for the ones that are reported?

**Comment by sheaushian** [comment]
I can confirm that sb_edac is not loaded with "lsmod" and also by running "rmmod sb_edac".
I was also evaluating EDAC on the broadwell-de together with mcelog and EDAC requires the kernel config option as attached for the broadwell-de.
The config options CONFIG_EDAC, CONFIG_EDAC_SUPPORT, CONFIG_EDAC_MM_EDAC and CONFIG_EDAC_SBRIDGE are not set.
[edac_config.txt](https://github.com/andikleen/mcelog/files/254430/edac_config.txt)

Attached is the full mcelog output for the following errors in sequence.
- bus/IOMCA
- unknown
- correctable DIMM/Socket
- cache yellow
- page
- uncorrectable error (tolerant set to 3)

The uncorrectable error did not generate a panic or is logged in the attached log.
[mcelog.txt](https://github.com/andikleen/mcelog/files/254618/mcelog.txt)

**Comment by aegl** [comment]
I think your uncorrected error is following the machine check path (do_machine_check() rather than machine_check_poll()). Since you have set tolerant to 3, the initial severity analysis in mce_no_way_out() decides that we aren't going to crash, so no_way_out is set to 0.

When we get to here (this is pure v3.19, your line numbers may vary):

1083                 /*
1084                  * Non uncorrected or non signaled errors are handled by
1085                  * machine_check_poll. Leave them alone, unless this panics.
1086                  */
1087                 if (!(m.status & (cfg->ser ? MCI_STATUS_S : MCI_STATUS_UC)) &&
1088                         !no_way_out)
1089                         continue;

the code decides to skip the error because you are running on a system with MCG_CAP{24} set, so cfg->ser says to look at the MCI_STATUS_S bit in the injected error. The GENMEM command doesn't set this bit.

Andi: I think this is a bug in GENMEM.

**Comment by aegl** [comment]
P.S. It should probably set MCI_STATUS_EN too.

**Comment by sheaushian** [comment]
Thanks. This works.
I modified the following in the GENMEM script to set both MCI_STATUS_S and MCI_STATUS_EN bit and uncorrectable errors are now reported.
ucflag=$[(1 << (61-32)) + (1 << (60-32)) + (1 << (56-32))]

mcelog --client output as attached
[mcelog_client_uc.txt](https://github.com/andikleen/mcelog/files/256253/mcelog_client_uc.txt)

mcelog with the uncorrectable error
[mcelog_uc.txt](https://github.com/andikleen/mcelog/files/256257/mcelog_uc.txt)

**Comment by andikleen** [comment]
Thanks. Fixed in 43656685015
